server:
  # please don't modify it if you don't know what you are doing
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jianpiao
    username:
    password:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  flyway:
    baseline-on-migrate: true

  thymeleaf:
    mode: HTML

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

sa-token:
  #token名称 (同时也是cookie名称)
  token-name: jptoken
  # token风格
  token-style: uuid
  #关闭读取Cookie中Token
  isReadCookie: true