insert into public.cinema_film (id, cinema_id, film_id, status) values ('1','1','1','showing');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('2','1','2','seal');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('3','1','3','showing');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('4','2','1','seal');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('5','2','2','showing');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('6','2','3','seal');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('7','3','1','showing');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('8','3','2','seal');
insert into public.cinema_film (id, cinema_id, film_id, status) values ('9','3','3','showing');
