-- ----------------------------
-- Table structure for role_permission
-- ----------------------------
CREATE TABLE IF not EXISTS "public"."role_permission" (
    "role_id" int4 NOT NULL,
    "permission_id" int4 NOT NULL
)
;
ALTER TABLE "public"."role_permission" OWNER TO "postgres";

-- ----------------------------
-- Records of role_permission
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tb_action
-- ----------------------------
CREATE TABLE IF not EXISTS "public"."tb_action" (
      "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
  INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
      "code" varchar(255) COLLATE "pg_catalog"."default",
      "name" varchar(255) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."tb_action" OWNER TO "postgres";

-- ----------------------------
-- Records of tb_action
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tb_module
-- ----------------------------
CREATE TABLE IF not EXISTS "public"."tb_module" (
      "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
  INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
      "code" varchar(255) COLLATE "pg_catalog"."default",
      "name" varchar(255) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."tb_module" OWNER TO "postgres";

-- ----------------------------
-- Records of tb_module
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tb_permission
-- ----------------------------
CREATE TABLE IF not EXISTS "public"."tb_permission" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
      INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "action_id" int4,
  "module_id" int4
)
;
ALTER TABLE "public"."tb_permission" OWNER TO "postgres";

-- ----------------------------
-- Records of tb_permission
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tb_role
-- ----------------------------
CREATE TABLE IF not EXISTS "public"."tb_role" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "role_name" varchar(255) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."tb_role" OWNER TO "postgres";

-- ----------------------------
-- Records of tb_role
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tb_user
-- ----------------------------
CREATE TABLE IF not EXISTS "public"."tb_user" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
    "email" varchar(255) COLLATE "pg_catalog"."default",
    "gender" varchar(255) COLLATE "pg_catalog"."default",
    "name" varchar(255) COLLATE "pg_catalog"."default",
    "nickname" varchar(255) COLLATE "pg_catalog"."default",
    "password" varchar(255) COLLATE "pg_catalog"."default",
    "photo" varchar(255) COLLATE "pg_catalog"."default",
    "tel" varchar(255) COLLATE "pg_catalog"."default",
    "username" varchar(255) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."tb_user" OWNER TO "postgres";

-- ----------------------------
-- Records of tb_user
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for user_role
-- ----------------------------
CREATE TABLE IF not EXISTS "public"."user_role" (
      "user_id" int4 NOT NULL,
      "role_id" int4 NOT NULL
)
;
ALTER TABLE "public"."user_role" OWNER TO "postgres";

-- ----------------------------
-- Records of user_role
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Primary Key structure for table role_permission
-- ----------------------------
ALTER TABLE "public"."role_permission" ADD CONSTRAINT "role_permission_pkey" PRIMARY KEY ("role_id", "permission_id");

-- ----------------------------
-- Auto increment value for tb_action
-- ----------------------------
SELECT setval('"public"."tb_action_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table tb_action
-- ----------------------------
ALTER TABLE "public"."tb_action" ADD CONSTRAINT "tb_action_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for tb_module
-- ----------------------------
SELECT setval('"public"."tb_module_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table tb_module
-- ----------------------------
ALTER TABLE "public"."tb_module" ADD CONSTRAINT "tb_module_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for tb_permission
-- ----------------------------
SELECT setval('"public"."tb_permission_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table tb_permission
-- ----------------------------
ALTER TABLE "public"."tb_permission" ADD CONSTRAINT "tb_permission_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for tb_role
-- ----------------------------
SELECT setval('"public"."tb_role_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table tb_role
-- ----------------------------
ALTER TABLE "public"."tb_role" ADD CONSTRAINT "tb_role_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for tb_user
-- ----------------------------
SELECT setval('"public"."tb_user_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table tb_user
-- ----------------------------
ALTER TABLE "public"."tb_user" ADD CONSTRAINT "tb_user_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table user_role
-- ----------------------------
ALTER TABLE "public"."user_role" ADD CONSTRAINT "user_role_pkey" PRIMARY KEY ("user_id", "role_id");

-- ----------------------------
-- Foreign Keys structure for table role_permission
-- ----------------------------
ALTER TABLE "public"."role_permission" ADD CONSTRAINT "fkop12osrj5s8tjrtax7psq4iod" FOREIGN KEY ("permission_id") REFERENCES "public"."tb_permission" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."role_permission" ADD CONSTRAINT "fksoh92u97x5i0ovrnnettbl8jn" FOREIGN KEY ("role_id") REFERENCES "public"."tb_role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table tb_permission
-- ----------------------------
ALTER TABLE "public"."tb_permission" ADD CONSTRAINT "fk33co2d7af1w2w9pq36cew7wwu" FOREIGN KEY ("action_id") REFERENCES "public"."tb_action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_permission" ADD CONSTRAINT "fklc95yc7f13y1exefpscfsobh4" FOREIGN KEY ("module_id") REFERENCES "public"."tb_module" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table user_role
-- ----------------------------
ALTER TABLE "public"."user_role" ADD CONSTRAINT "fk430om9qnxgilp5cvcbeyovi37" FOREIGN KEY ("user_id") REFERENCES "public"."tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."user_role" ADD CONSTRAINT "fkeayxeqvq6j9yuf6ogfgvr9u6" FOREIGN KEY ("role_id") REFERENCES "public"."tb_role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

